### ISSUE TITLE
Pc 

### ISSUE THREAD

**Issue by kimlarastr** [th-koeln/mi-bachelor-gdvk#16]
Mein Pc verbindet zurzeit nicht mit eduroam und ich bin heute im Figma Workshop. Geht das auch ohne Internet? Ansonsten bräuchte ich einen Computer.

**Comment by vschaefer** [comment]
Hello, das ist kein Problem. Raum 3.204 ist mit Rechnern ausgestattet.

**Comment by kimlarastr** [comment]
Super danke!
