### ISSUE TITLE
Freigabe kommender Workshops/Trainings

### ISSUE THREAD

**Issue by dkathmann** [th-koeln/mi-bachelor-gdvk#17]
Ich wollte kurz fragen, ob es einen konkreten Termin gibt, ab dem die kommenden Workshops bzw. Trainings zur Anmeldung freigeschaltet werden.

**Comment by vschaefer** [comment]
Hallo,

auf jeden Fall noch diese Woche. Ich werde in diesem Issue hier eine Nachricht hinterlassen, sobald ich die Termine eingetragen habe.

LG

**Comment by vschaefer** [comment]
Hello,

die Termine für nächste Woche sind jetzt buchbar.

**Comment by dkathmann** [comment]
Danke für die Info.

Sagst du bei den weiteren Freischaltungen auch hier im Ticket Bescheid, oder läuft das anders?

**Comment by vschaefer** [comment]
Ich kann das hier gerne reinschreiben, wenn ich weitere Termine einstelle.

**Comment by dkathmann** [comment]
Das wäre wirklich zuvorkommend; vielen Dank.

**Comment by vschaefer** [comment]
Die Termine für kommende Woche sind jetzt alle buchbar.

**Comment by vschaefer** [comment]
Die Termine für den 08. und 09. Juni sind jetzt buchbar.
