### ISSUE TITLE
Workshop-Termin-Konflikt mit dem Semesterplan

### ISSUE THREAD

**Issue by dkathmann** [th-koeln/mi-bachelor-gdvk#18]
Mir ist gerade aufgefallen, dass laut dem [Semesterplan Informatik SS 2017](https://www.th-koeln.de/mam/downloads/deutsch/hochschule/fakultaeten/informatik_und_ingenieurwissenschaften/semesterplan_informatik_ss_17.pdf) vom 02.06.17 bis zum 06.06.17 keine Vorlesungen stattfinden sollen, was aber mit den Workshop-Terminen am 02.06.17 kollidiert.

Ist der Semesterplan fehlerhaft, oder wurden die Termine fälschlicherweise eingetragen?

**Comment by vschaefer** [comment]
Hallo, du hast vollkommen Recht. Der 02.06. zählt als Anreisetag für Pfingsten. Wir haben an dem Tag keine Pflichttermine und euch ist es damit freigestellt, ob ihr an den Veranstaltungen teilnimmt.

Falls ihr den 02.06. als Anreisetag eingeplant habt und ihr dadurch eine Veranstaltung verpasst, die an dem Tag stattfindet, dann gibt uns darüber Bescheid. Wir werden dann versuchen, den Workshop oder das Training in der darauffolgenden Woche noch mal anzubieten.

**Comment by dkathmann** [comment]
Danke für die Antwort; gut zu wissen.
