### ISSUE TITLE
Affinity Designer

### ISSUE THREAD

**Issue by dkathmann** [th-koeln/mi-bachelor-gdvk#20]
@fl-thkoeln ich wäre daran interessiert, eine Lizenz für Affinity Designer (evlt. auch für Affinity Photo) zu erwerben. Ich wollte jetzt wissen, ob es möglich ist, über die TH Köln günstigere Studenten-Lizenzen zu bekommen. Auf der [entsprechenden Seite](https://affinity.serif.com/de/education/) sind neue Lizenzmodelle für Anfang 2017 angekündigt gewesen, bisher gibt es aber noch keine konkreten Informationen und über die Kontaktmail habe ich bisher keine Antwort bekommen.

**Comment by netzfluencer** [comment]
@d4v3k also ich hatte damals mal gefragt. Über die TH bekommt man anscheinend nur Lizenzen die man an der Einrichtung selber nutzen kann. Leider gibt es auch noch keine Lizenzen mit Studentenrabatt. Gerade läuft aber ne Rabatt Aktion allgemein. Man zahlt im Moment nur 44€ je Programm-Lizenz (Normaler Preis war 55€).

**Comment by fl-thkoeln** [comment]
... oder man wartet darauf, das Serif die Bildungslizenzen anbietet. Wüsste aber auch nicht, dass über TH Lizenzen zum Eigengebrauch bezogen werden könnten.
