### ISSUE TITLE
Letzter Feedback-Termin

### ISSUE THREAD

**Issue by dkathmann** [th-koeln/mi-bachelor-gdvk#25]
Der letzte Feedback-Termin am 21.09. ist ja leider schon seit längerem komplett voll. Ich habe nun von einigen Kommilitonen gehört, dass man bei den letzten Terminen auch kommen konnte, obwohl sie bereits ausgebucht waren; wird dies beim letzten Termin wieder so gehandhabt?

**Comment by cnoss** [comment]
EIgentlich nicht … aber nu isses ja vorbei
