### ISSUE TITLE
Styleguide Begründungen

### ISSUE THREAD

**Issue by dkathmann** [th-koeln/mi-bachelor-gdvk#26]
Zu meiner Überraschung habe ich die Tage von einigen Kommilitonen gehört, dass in den letzten Feedback-Terminen gesagt wurde, dass im Styleguide ausgiebige Begründungen zu den verwendeten Gestaltungselementen aufgeführt werden sollen. Das hatte ich aus den Vorlesungen und Workshops so nicht mitbekommen. Aus den Niveaustufen kann ich dies auch nicht herauslesen; höchstens, dass beschrieben wird, wie die aufgeführten Elemente genau anzuwenden sind. 

Ich würde mich diesbezüglich über eine Klarstellung freuen.

**Comment by cnoss** [comment]
Nein. Wie heute besprochen. Beschreibungen sind absolut ausreichend. Das Ding soll so kompakt wie möglich sein.
